In [2]:
import numpy as np

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
N = 10
np_arange = np.arange(N-1, -1, -1)
np_arange

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [17]:
np_arange = np.arange(N,-1,-1)
print("Элементы от N до нуля: ",np_arange, '\n')

np_diag = np.diag(np_arange, k=0)
print('Диагональная матрица с элементами np_arange на диагонали:\n\n',np_diag)

diag_sum = 0

for i in range(np_diag.shape[0]):
    diag_sum += np_diag[i][i]
    
print(f'\nСумма диагонали матрицы равна {diag_sum}')

Элементы от N до нуля:  [10  9  8  7  6  5  4  3  2  1  0] 

Диагональная матрица с элементами np_arange на диагонали:

 [[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]

Сумма диагонали матрицы равна 55


## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [32]:
# коэффициенты при переменных в левой части уравнения
a = np.array([
    [4, 2, 1],
    [1, 3, 0],
    [0, 5, 4]
]
)

# значения в правой части уравнения
b = np.array([4, 12, 3])

# решение
from numpy import linalg

x, y, z = linalg.solve(a, b)
print(f'x = {x:.2}, y = {y:.2}, z = {z:.2}')

# проверка корректности
flag = np.allclose(np.dot(a, [x, y, z]), b )
if flag:
    print('Решение верное')
else:
    print('Решение неверное!')

x = 0.067, y = 4.0, z = -4.2
Решение верное


## Задача 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array

In [35]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [5]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [33]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [48]:
#поищем максимальный косинус и запишем, в какой строке он был получен, в переменную num_max
max_cosine = cosine(next_user_stats, users_stats[0])
num_max = 0
for i in range(1,len(users_stats)):
    next_cosine = cosine(next_user_stats, users_stats[i])
    if max_cosine < next_cosine:
        max_cosine = next_cosine
        num_max = i

print(f'Пришёл новый посетитель со статистикой:\n{next_user_stats}\n')
print(f'Самый похожий пользователь с очередным посетителем - в строке {num_max} матрицы users_stats с косинусом {max_cosine}\n')
print(f'Его статистика:\n{users_stats[num_max]}')

Пришёл новый посетитель со статистикой:
[0 1 2 0 0 0]

Самый похожий пользователь с очередным посетителем - в строке 7 матрицы users_stats с косинусом 0.9486832980505138

Его статистика:
[0 1 1 0 0 0]
